name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  build:
    name: Make tor
    runs-on: ubuntu-latest
    container: mirisbowring/texlive_ctan_full:2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: latexmk -f -pdf tor/main.tex -cd
      - name: Save PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf.zip
          path: tor/main.pdf

